# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: "Scorecards supply-chain security"

on:
  push:
    branches: [ "main", "master" ]
  schedule:
    - cron: "0 6 * * *"

# Declare default permissions as read only.
permissions: read-all

jobs:
  analysis:
    name: Scorecards analysis
    runs-on: ubuntu-latest
    permissions:
      # Needed to upload results to code-scanning dashboard.
      security-events: write
      # Needed to fetch the correct commit.
      contents: read
      # Needed to calculate criticality score.
      id-token: write

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: "Run security analysis"
        uses: ossf/scorecard-action@v5.1.1
        with:
          results_file: results.sarif.json
          results_format: sarif
          publish_results: true

      # Upload the results as artifacts (optional).
      - name: "Upload results"
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif.json

      # Upload the results to GitHub's code scanning dashboard (optional).
      # Commenting out will disable upload of results to your repo's Code Scanning dashboard
      - name: "Upload to code-scanning"
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: results.sarif.json # Corrected line
